### ISSUE TITLE
Nightly CUDA Build Failing

### ISSUE THREAD

**Issue by JWhitleyWork** [Autoware-AI/docker#12]
See the logs from the last 3 nightly runs at https://github.com/Autoware-AI/docker/actions?query=workflow%3A%22Nightly+build%22. It's related to a Docker layer not existing but I can't reproduce it locally. @sgermanserrano can you look into this? I'm tied up with AVP stuff in Auto right now.

**Comment by sgermanserrano** [comment]
some googling shows that it seems to be a docker issue when doing multiple COPY one after another on a clean run [(docker-failed-to-export-image-failed-to-create-image-failed-to-get-layer)](https://stackoverflow.com/questions/51115856/docker-failed-to-export-image-failed-to-create-image-failed-to-get-layer), from the comments online a second run would clear the problem but for the CI we are always starting on a clean slate.

The link above contains another possible solution by adding `RUN true` between `COPY` but it doesn't look like we need it at the moment as flipping the commands does the trick

**Comment by JWhitleyWork** [comment]
Seems to be fixed. Closing.
