### ISSUE TITLE
Wrong operator on checking CUDA installation in install_tvm.sh

### ISSUE THREAD

**Issue by LucaFos** [Autoware-AI/docker#16]
### Required information:
- Autoware version or commit hash
  - e4b2cadd9c2d5cfd3c1f68ec81ccdf8833afbfa0

### Description of the bug
We need a "-d" operator instead of a "-f" operator when checking for the CUDA folder. This is done in https://github.com/Autoware-AI/docker/blob/master/generic/install_tvm.sh#L51.

**Comment by JWhitleyWork** [comment]
Closed by #17.
