### ISSUE TITLE
Enable CUDA on arm64

### ISSUE THREAD

**Issue by ambroise-arm** [Autoware-AI/docker#21]
### Description
Provide docker support for CUDA on arm64.
Currently, there is support for arm64 native build of the base Docker image, but not with CUDA.

### Implementation considerations
Given the binaries provided by nvidia, only melodic can benefit from this addition.
A new Dockerfile is required to build a CUDA environment natively.

A complete support would imply a cross-build Dockerfile too. For development purposes, a native build is a good first step.

**Comment by JWhitleyWork** [comment]
@ambroise-arm Unfortunately, we can't accept this feature. 1.15.0 will be the last feature-release for Autoware.AI and the MR deadline for 1.15.0 has already passed.
