### ISSUE TITLE
The tag 1.13.0 moved

### ISSUE THREAD

**Issue by filiperinaldi** [Autoware-AI/docker#9]
The tag **1.13.0** is now pointing to **1.14.0** instead of its original commit (e4736e24c6a0eb643e5114ff263903e8f50440f1).
Unfortunately this has spread into Dockerhub and the original autoware/autoware:melodic-1.13.0 also changed.

I suppose this was a mistake during Gitlab -> Github transition(?)

**Comment by sgermanserrano** [comment]
@filiperinaldi this has been fixed now. I think we can close this issue

**Comment by JWhitleyWork** [comment]
@filiperinaldi

**Comment by JWhitleyWork** [comment]
@filiperinaldi / @sgermanserrano This was done intentionally. We don't consider the Docker repository or CI to be parts of the actual release. The tags on this repository are just there to generate containers with the correct source code. This tag was moved forward to fix a couple of bugs but it doesn't reall matter on what commit the tags reside in this repository. I'm going to move both 1.13.0 and 1.14.0 up to the latest commit on this repo to generate containers which have some critical bug fixes.

**Comment by filiperinaldi** [comment]
If tags and their produced Docker images change randomly, then we can no longer use autoware docker images as stable base images in Dockerfiles (e.g. FROM autoware/autoware:v1.13-melodic). The reason I raised this issue was because the re-tagging of 1.13 to 1.14 broke our workflow due to the new autoware image adding "USER autoware" causing all "RUN apt-get" to fail.

Just to emphasise what I mean, for example the Autoware project itself could suffer from the same issues if the ROS project was randomly updating their docker images.

The version of the docker tags on the Docker repo are still important to version the docker tooling and scripts.

What is the con in tagging the docker repo together with the rest of the project? Doing a patch fix to the docker will require all repos to be tagged but if it is a fix deemed important then it sounds the right thing.

**Comment by JWhitleyWork** [comment]
@filiperinaldi You are, of course, correct. I'm sorry for the confusion. For future releases, we will consider the `docker` repository part of the official release and will not move tags. For the time being, 1.13.0 and 1.14.0 both point to the same commit to fix a critical bug which was found in 1.13.0. If this is too problematic, I can move it back, but work-arounds will be required by others so I would prefer not to at this time, if possible. Please let me know. 1.12.0 and before should be unaffected.

**Comment by filiperinaldi** [comment]
Hi Josh, we will push a workaround on our side for 1.13.
Thanks,
Filipe

**Comment by filiperinaldi** [comment]
Hi Josh, we will push a workaround on our side for 1.13.
Thanks,
Filipe
